[project]
name = 'alt-contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Dao-access]
path = 'contracts/Dao-access.clar'
clarity_version = 3
epoch = 3.0

[contracts.alttoken]
path = 'contracts/alttoken.clar'
clarity_version = 3
epoch = 3.0

[contracts.governance]
path = 'contracts/governance.clar'
clarity_version = 3
epoch = 3.0

[contracts.proposal]
path = 'contracts/proposal.clar'
clarity_version = 3
epoch = 3.0

[contracts.proposal-registry]
path = 'contracts/proposal-registry.clar'
clarity_version = 3
epoch = 3.0

[contracts.transparent-fund-allocation]
path = 'contracts/transparent-fund-allocation.clar'
clarity_version = 1
epoch = 2.05

[contracts.treasury]
path = 'contracts/treasury.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
